### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by txl263** [PyUserInput/PyUserInput#27]
```>>> from pymouse import PyMouse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python27\lib\site-packages\pymouse\__init__.py", line 38, in <module>
    from .windows import PyMouse, PyMouseEvent
  File "D:\Python27\lib\site-packages\pymouse\windows.py", line 17, in <module>
    import win32api
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。```

**Comment by georgePadolsey** [comment]
With a bit of google-fu (🐱‍👤), it seems this is due to you having 64 bit python though 32 bit pywin32 or vice versa (32bit python with 64bit pywin32). You need to make sure you install the right-bit version of pywin32 and this should dissapear (make sure to uninstall the wrong version!)

You can also use pyHook as suggested by the [readme](https://github.com/PyUserInput/PyUserInput#dependencies) as another option  (am assuming you're running on windows).
