### ISSUE TITLE
PyMouseEvent hangs when calling .stop()

### ISSUE THREAD

**Issue by Lonami** [PyUserInput/PyUserInput#31]
Hey, pretty cool library! I bet it must not be easy to handle so many operative systems, so kudos. Anyway, I have a problem on my `PyMouseEvent` subclass, calling `self.stop()` just hangs. Here's the traceback when I <kbd>Ctrl+C</kbd> twice:
```
Traceback (most recent call last):
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 191, in run
    self.display2.record_enable_context(self.ctx, self.handler)
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/ext/record.py", line 243, in enable_context
    context = context)
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/ext/record.py", line 220, in __init__
    rq.ReplyRequest.__init__(self, *args, **keys)
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1381, in reply
    self._display.send_and_recv(request = self._serial)
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 613, in send_and_recv
    gotreq = self.parse_response(request)
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 705, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 793, in parse_request_response
    req._parse_response(self.data_recv[:self.recv_packet_len])
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/ext/record.py", line 224, in _parse_response
    self._callback(r)
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 214, in handler
    self.click(event.root_x, event.root_y, translate_button_code(event.detail), True)
  File "hax.py", line 60, in click
    self.stop()
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 203, in stop
    d.record_disable_context(self.ctx)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 55, in manager
    display.sync()
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/display.py", line 182, in sync
    self.get_pointer_control()
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/display.py", line 833, in get_pointer_control
    return request.GetPointerControl(display = self.display)
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1382, in reply
    self._response_lock.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hax.py", line 74, in <module>
    print(CoordAsker.ask(2))
  File "hax.py", line 71, in ask
    a.run()
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 194, in run
    self.stop()
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 203, in stop
    d.record_disable_context(self.ctx)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 55, in manager
    display.sync()
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/display.py", line 182, in sync
    self.get_pointer_control()
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/display.py", line 833, in get_pointer_control
    return request.GetPointerControl(display = self.display)
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/lonami/.local/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1377, in reply
    while self._data is None and self._error is None:
KeyboardInterrupt
```

Not sure what's going on so decided to open up an issue. I appreciate any help, and understand if it gets closed due to it being a problem with my system :)

**Comment by TheoRet** [comment]
Hello, I am using Linux Mint 18.

I had a similar issue, when calling the self.stop method inside a function triggered by a key or mouse button.  the script hangs and starts occupying all the processor power

Workaround - calling stop from a separate thread:
```
x=threading.Thread(target=my_event_listener.stop)
x.start()
```

Still, the problem occurs when trying to terminate the PyMouseEvent-Listener or the PyKeyboardEvent-Listener by pressing escape (built-in function). I could disable this by re-defining the following method:
```
def escape():
    return False
```

Hope that can help you!

**Comment by Lonami** [comment]
Thanks! If I change the Clickonacci's stop example:
```python
from pymouse import PyMouseEvent

def fibo():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

class Clickonacci(PyMouseEvent):
    def __init__(self):
        PyMouseEvent.__init__(self)
        self.fibo = fibo()

    def click(self, x, y, button, press):
        if button == 1 and press:
            print(next(self.fibo))
        elif button != 1:
            self.stop()

C = Clickonacci()
C.run()
```

For this:
```python
            Thread(target=lambda: self.stop()).start()
```

It "works". I actually get:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "findsq.py", line 24, in <lambda>
    Thread(target=lambda: self.stop()).start()
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 203, in stop
    d.record_disable_context(self.ctx)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/lonami/.local/lib/python3.6/site-packages/pymouse/x11.py", line 58, in manager
    raise X11Error(errors)
pymouse.x11.X11Error: [(XError(<Xlib.display._BaseDisplay object at 0x7f650dc6ceb8>, b'\x00\x99\x11\x00\x00\x00@\x04\x06\x00\x92\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), None)]
```

But it surely doesn't block like this :)
