### ISSUE TITLE
Can't send function key above 12 in Linux?

### ISSUE THREAD

**Issue by sclarkso** [PyUserInput/PyUserInput#38]
`Traceback (most recent call last):
  File "test5.py", line 30, in keep_awake
    k.tap_key(k.function_keys[13])
  File "/home/sclarkso/.local/lib/python2.7/site-packages/pykeyboard/base.py", line 43, in tap_key
    self.press_key(character)
  File "/home/sclarkso/.local/lib/python2.7/site-packages/pykeyboard/x11.py", line 73, in press_key
    self._handle_key(character, X.KeyPress)
  File "/home/sclarkso/.local/lib/python2.7/site-packages/pykeyboard/x11.py", line 60, in _handle_key
    fake_input(d, event, character)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/sclarkso/.local/lib/python2.7/site-packages/pymouse/x11.py", line 58, in manager
    raise X11Error(errors)
pymouse.x11.X11Error: [(BadValue(), None)]`

**Comment by sclarkso** [comment]
Any value <= 12 doesn't error.

**Comment by pepijndevos** [comment]
This is a problem in Xlib, not much we can do about it, unless you know the correct keycodes for them.
You can directly pass keycodes to tap_key, but you'd have to find what they are first.
Try the below code, and you'll find that Xlib gives you 0 for the higher function keys.

```
import Xlib.XK
from Xlib.display import Display
d = Display() 
d.keysym_to_keycode(Xlib.XK.string_to_keysym("F13"))
```
